MAP_LAYOUT = [['sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand'],
              ['sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand'],
              ['sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand'],
              ['sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand'],
              ['sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand'],
              ['sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand'],
              ['sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand'],
              ['sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand'],
              ['sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand'],
              ['sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand'],
              ['sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand','sand']]